export const calendar_MonthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
export const calendar_MonthNamesShort = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
export const calendar_DayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
export const calendar_DayNamesShort = ["S", "M", "T", "W", "T", "F", "S"];
export const schedule_ViewMenu = 'View Menu'
export const schedule_SkipWeeks = 'Skip Weeks'
export const schedule_ChangeMealsOrSkip = 'Change meals or skip week by:'
export const schedule_UnskipWeekBy = 'Unskip week by:'
export const schedule_UnskipWeek = 'Unskip Week'
export const schedule_BoxStatus = 'Box Status:'
export const schedule_Delivered = 'Delivered'
export const schedule_Skipped = 'Skipped'
export const schedule_Shipped = 'Shipped'
export const schedule_PreparingMeals = 'Preparing Meals'
export const schedule_BuyingIngredients = 'Buying Ingredients'
export const schedule_CreatingOrders = 'Creating Orders'
export const schedule_WaitingForDelivery = 'Waiting for delivery'
